Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "myhost"
  #config.vm.network "private_network", ip: "192.168.50.10"
  #config.vm.synced_folder "src/", "/var/www/html"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end
end