Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "myhost"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision "file", source: "../../", destination: "$HOME/kafka-topology-builder"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end
end