#!/usr/bin/env bash

mkdir -p /usr/local/julie-ops/bin

if id "julie-kafka" &>/dev/null;
then
  echo "User julie-kafka already exist"
else
   addgroup --system julie-kafka
   adduser --system --no-create-home  --ingroup julie-kafka julie-kafka
fi
