micronaut:
  openapi:
    target:
      file: openapi-spec.yml
    property:
      naming:
        strategy: KEBAB_CASE
  router:
    static-resources:
      swagger:
        paths:
          - classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
  application:
    name: Kafka Topology Builer API
    topology: topologies/topology-for-cloud.yaml
  topology_builder:
    brokers_list: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"
    allow_delete: true
    admin_config_file: "${CONFIG_FILE:admin.properties}"
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
