#!/usr/bin/env bash

ARTIFACT="kafka-topology-builder-jar-with-dependencies.jar"

if
 [ -z "$KAFKA_TOPOLOGY_HOME" ]; then
  KAFKA_TOPOLOGY_HOME="/usr/local/kafka-topology-builder/bin"
fi


if
 [ -z "$KAFKA_HEAP_OPTS" ]; then
  KAFKA_HEAP_OPTS="-Xmx512M"
fi

# Which java to use
if [ -z "$JAVA_HOME" ]; then
  JAVA="java"
else
  JAVA="$JAVA_HOME/bin/java"
fi

JAR_PATH="$KAFKA_TOPOLOGY_HOME/$ARTIFACT"

exec $JAVA $KAFKA_HEAP_OPTS -jar $JAR_PATH "$@"