# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI tests (legacy)

on:
  push:
    branches:
      - 2.x
      - 2.0.x
      - 2.1.x
  pull_request:
    branches:
      - 2.x
      - 2.0.x
      - 2.1.x
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up the JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml